namespace RegistrationApp.Models;

/// <summary>
/// Represents a Razorpay webhook payload for payment.authorized events
/// </summary>
public class RazorpayWebhookPayload
{
    /// <summary>
    /// Unique webhook event ID
    /// </summary>
    public string? Id { get; set; }

    /// <summary>
    /// Event type (e.g., "payment.authorized")
    /// </summary>
    public string? Event { get; set; }

    /// <summary>
    /// When the event occurred (Unix timestamp)
    /// </summary>
    public long CreatedAt { get; set; }

    /// <summary>
    /// Payment details from Razorpay
    /// </summary>
    public PaymentData? Payload { get; set; }
}

/// <summary>
/// Represents the payment data within a Razorpay webhook
/// </summary>
public class PaymentData
{
    /// <summary>
    /// Payment entity details
    /// </summary>
    public PaymentEntity? Payment { get; set; }
}

/// <summary>
/// Represents a payment entity from Razorpay
/// </summary>
public class PaymentEntity
{
    /// <summary>
    /// Unique payment ID generated by Razorpay
    /// </summary>
    public string? Id { get; set; }

    /// <summary>
    /// Associated order ID (registration ID sent to Razorpay)
    /// </summary>
    public string? OrderId { get; set; }

    /// <summary>
    /// Payment amount in the smallest currency unit (paise for INR)
    /// </summary>
    public long Amount { get; set; }

    /// <summary>
    /// Currency code (e.g., "INR")
    /// </summary>
    public string? Currency { get; set; }

    /// <summary>
    /// Payment status (e.g., "authorized", "captured", "failed")
    /// </summary>
    public string? Status { get; set; }

    /// <summary>
    /// Method used for payment (e.g., "netbanking", "card", "wallet")
    /// </summary>
    public string? Method { get; set; }

    /// <summary>
    /// Customer email
    /// </summary>
    public string? Email { get; set; }

    /// <summary>
    /// Customer contact
    /// </summary>
    public string? Contact { get; set; }

    /// <summary>
    /// Error code if payment failed
    /// </summary>
    public string? ErrorCode { get; set; }

    /// <summary>
    /// Error description if payment failed
    /// </summary>
    public string? ErrorDescription { get; set; }

    /// <summary>
    /// When the payment was created (Unix timestamp)
    /// </summary>
    public long CreatedAt { get; set; }
}
